// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/msg_authorization/v1beta1/msg_authorization.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenericCapability grants the permission to execute any transaction of the provided
// sdk.Msg type without restrictions
type GenericCapability struct {
	Msg *types.Any `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty" yaml:"msg_type"`
}

func (m *GenericCapability) Reset()         { *m = GenericCapability{} }
func (m *GenericCapability) String() string { return proto.CompactTextString(m) }
func (*GenericCapability) ProtoMessage()    {}
func (*GenericCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor_34394388a9210393, []int{0}
}
func (m *GenericCapability) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenericCapability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenericCapability.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenericCapability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericCapability.Merge(m, src)
}
func (m *GenericCapability) XXX_Size() int {
	return m.Size()
}
func (m *GenericCapability) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericCapability.DiscardUnknown(m)
}

var xxx_messageInfo_GenericCapability proto.InternalMessageInfo

type CapabilityGrant struct {
	Capability *types.Any `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Expiration int64      `protobuf:"varint,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (m *CapabilityGrant) Reset()         { *m = CapabilityGrant{} }
func (m *CapabilityGrant) String() string { return proto.CompactTextString(m) }
func (*CapabilityGrant) ProtoMessage()    {}
func (*CapabilityGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_34394388a9210393, []int{1}
}
func (m *CapabilityGrant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CapabilityGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CapabilityGrant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CapabilityGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilityGrant.Merge(m, src)
}
func (m *CapabilityGrant) XXX_Size() int {
	return m.Size()
}
func (m *CapabilityGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilityGrant.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilityGrant proto.InternalMessageInfo

func (m *CapabilityGrant) GetCapability() *types.Any {
	if m != nil {
		return m.Capability
	}
	return nil
}

func (m *CapabilityGrant) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type SendCapability struct {
	SpendLimit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=spend_limit,json=spendLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"spend_limit" yaml:"spend_limit"`
}

func (m *SendCapability) Reset()         { *m = SendCapability{} }
func (m *SendCapability) String() string { return proto.CompactTextString(m) }
func (*SendCapability) ProtoMessage()    {}
func (*SendCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor_34394388a9210393, []int{2}
}
func (m *SendCapability) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendCapability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendCapability.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SendCapability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCapability.Merge(m, src)
}
func (m *SendCapability) XXX_Size() int {
	return m.Size()
}
func (m *SendCapability) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCapability.DiscardUnknown(m)
}

var xxx_messageInfo_SendCapability proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenericCapability)(nil), "cosmos.msg_authorization.v1beta1.GenericCapability")
	proto.RegisterType((*CapabilityGrant)(nil), "cosmos.msg_authorization.v1beta1.CapabilityGrant")
	proto.RegisterType((*SendCapability)(nil), "cosmos.msg_authorization.v1beta1.SendCapability")
}

func init() {
	proto.RegisterFile("cosmos/msg_authorization/v1beta1/msg_authorization.proto", fileDescriptor_34394388a9210393)
}

var fileDescriptor_34394388a9210393 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x48, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0xcf, 0x2d, 0x4e, 0x8f, 0x4f, 0x2c, 0x2d, 0xc9, 0xc8, 0x2f, 0xca, 0xac, 0x4a,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xc4, 0x94, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x80, 0xe8, 0xd4, 0xc3, 0x94, 0x87, 0xea, 0x94, 0x12, 0x49,
	0xcf, 0x4f, 0xcf, 0x07, 0x2b, 0xd6, 0x07, 0xb1, 0x20, 0xfa, 0xa4, 0x24, 0xd3, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0xc1, 0xbc, 0xa4, 0xd2, 0x34, 0xfd, 0xc4, 0xbc, 0x4a, 0x98, 0x14, 0xc4, 0xc8,
	0x78, 0x88, 0x1e, 0xa8, 0xf9, 0x10, 0x29, 0x39, 0xa8, 0x3b, 0x93, 0x12, 0x8b, 0x53, 0xe1, 0x4e,
	0x4b, 0xce, 0xcf, 0x84, 0xba, 0x46, 0x69, 0x32, 0x23, 0x97, 0xa0, 0x7b, 0x6a, 0x5e, 0x6a, 0x51,
	0x66, 0xb2, 0x73, 0x62, 0x41, 0x62, 0x52, 0x66, 0x4e, 0x66, 0x49, 0xa5, 0x50, 0x2a, 0x17, 0x73,
	0x6e, 0x71, 0xba, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xc4, 0x66, 0x3d, 0x98,
	0xcd, 0x7a, 0x8e, 0x79, 0x95, 0x4e, 0xb6, 0x9f, 0xee, 0xc9, 0xf3, 0x57, 0x26, 0xe6, 0xe6, 0x58,
	0x29, 0x81, 0x7c, 0x52, 0x52, 0x59, 0x90, 0xaa, 0x74, 0x6a, 0x8b, 0xae, 0x5a, 0x7a, 0x66, 0x49,
	0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0x2e, 0xd4, 0x21, 0x50, 0x4a, 0xb7, 0x38, 0x25, 0x5b, 0x1f,
	0xa4, 0xaa, 0x58, 0xcf, 0xb7, 0x38, 0x3d, 0x08, 0x64, 0xbe, 0x95, 0x78, 0xc7, 0x02, 0x79, 0x86,
	0x17, 0x0b, 0xe4, 0x19, 0x2f, 0x6d, 0xd1, 0xe5, 0x46, 0x58, 0xef, 0xa9, 0x54, 0xc1, 0xc5, 0x8f,
	0xe0, 0xba, 0x17, 0x25, 0xe6, 0x95, 0x08, 0xb9, 0x72, 0x71, 0x25, 0xc3, 0x85, 0xf0, 0xba, 0x8c,
	0xff, 0x14, 0xaa, 0x69, 0x41, 0x48, 0x1a, 0x85, 0xe4, 0xb8, 0xb8, 0x52, 0x2b, 0x0a, 0x32, 0x8b,
	0xc0, 0x21, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x24, 0xa2, 0xb4, 0x8e, 0x91, 0x8b,
	0x2f, 0x38, 0x35, 0x2f, 0x05, 0x29, 0x30, 0x9a, 0x18, 0xb9, 0xb8, 0x8b, 0x0b, 0x52, 0xf3, 0x52,
	0xe2, 0x73, 0x32, 0x73, 0x33, 0x4b, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x24, 0xf5, 0xa0,
	0xe1, 0x0c, 0x0a, 0x59, 0x58, 0xd4, 0xe9, 0x39, 0xe7, 0x67, 0xe6, 0x39, 0xb9, 0x9d, 0xb8, 0x27,
	0xcf, 0xf0, 0xe9, 0x9e, 0xbc, 0x10, 0x24, 0x78, 0x90, 0xf4, 0x2a, 0xad, 0xba, 0x2f, 0xaf, 0x41,
	0x44, 0x08, 0x81, 0x8c, 0x29, 0x0e, 0xe2, 0x02, 0xeb, 0xf4, 0x01, 0x69, 0xc4, 0x19, 0x54, 0x4e,
	0x01, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7,
	0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0x65, 0x86, 0xd7, 0xa2, 0x0a,
	0x2c, 0x49, 0x17, 0x6c, 0x79, 0x12, 0x1b, 0x38, 0x34, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x2b, 0xe4, 0x00, 0xaa, 0xe3, 0x02, 0x00, 0x00,
}

func (this *GenericCapability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenericCapability)
	if !ok {
		that2, ok := that.(GenericCapability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Msg.Equal(that1.Msg) {
		return false
	}
	return true
}
func (this *SendCapability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SendCapability)
	if !ok {
		that2, ok := that.(SendCapability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.SpendLimit) != len(that1.SpendLimit) {
		return false
	}
	for i := range this.SpendLimit {
		if !this.SpendLimit[i].Equal(&that1.SpendLimit[i]) {
			return false
		}
	}
	return true
}
func (m *GenericCapability) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenericCapability) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenericCapability) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgAuthorization(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CapabilityGrant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CapabilityGrant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CapabilityGrant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != 0 {
		i = encodeVarintMsgAuthorization(dAtA, i, uint64(m.Expiration))
		i--
		dAtA[i] = 0x10
	}
	if m.Capability != nil {
		{
			size, err := m.Capability.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMsgAuthorization(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SendCapability) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendCapability) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SendCapability) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SpendLimit) > 0 {
		for iNdEx := len(m.SpendLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SpendLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgAuthorization(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgAuthorization(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgAuthorization(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenericCapability) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovMsgAuthorization(uint64(l))
	}
	return n
}

func (m *CapabilityGrant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Capability != nil {
		l = m.Capability.Size()
		n += 1 + l + sovMsgAuthorization(uint64(l))
	}
	if m.Expiration != 0 {
		n += 1 + sovMsgAuthorization(uint64(m.Expiration))
	}
	return n
}

func (m *SendCapability) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SpendLimit) > 0 {
		for _, e := range m.SpendLimit {
			l = e.Size()
			n += 1 + l + sovMsgAuthorization(uint64(l))
		}
	}
	return n
}

func sovMsgAuthorization(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgAuthorization(x uint64) (n int) {
	return sovMsgAuthorization(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenericCapability) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenericCapability: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenericCapability: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CapabilityGrant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CapabilityGrant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CapabilityGrant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capability", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Capability == nil {
				m.Capability = &types.Any{}
			}
			if err := m.Capability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsgAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SendCapability) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgAuthorization
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendCapability: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendCapability: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpendLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgAuthorization
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpendLimit = append(m.SpendLimit, types1.Coin{})
			if err := m.SpendLimit[len(m.SpendLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgAuthorization(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgAuthorization
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgAuthorization(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgAuthorization
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgAuthorization
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgAuthorization
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgAuthorization
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgAuthorization
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgAuthorization        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgAuthorization          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgAuthorization = fmt.Errorf("proto: unexpected end of group")
)
